export const SliderData = [
  {
    image: "https://www.csrl.in/UploadedFiles/Project/rect3009.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/ct_ongc.jpeg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th1.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th2.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th3.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th5.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th4.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th7.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th6.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th9.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th8.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th10.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th11.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/noida-centre-home.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th13.jpg",
    image: "https://www.csrl.in/UploadedFiles/Project/project-th12.jpg",
  },
];
